### ISSUE TITLE
Hints not appearing

### ISSUE THREAD

**Issue by pokrakam** [exercism/abap#123]
Question for the Exercism folk - @ErikSchierboom can you help?
I added a hints file but it is not appearing in the exercise. 
https://github.com/exercism/abap/blob/main/exercises/practice/custom-signs/.docs/hints.md

I copied the JS one and rewrote the content, figuring if I start from a working example it should be OK. 

It's the first hints file on the track, so am wondering if there is a config.json setting or something? Didn't see anything in the JS track or in the contributor documentation.

**Comment by ErikSchierboom** [comment]
This is because the original exercise was a concept exercise but it is ported to a practice exercise. Practice exercises can't (yet) have tasks, but the hints are all linked to specific tasks. You can "fix" this by moving all the hints in a `## General` heading.

This is one of the reasons why I'd suggest not to port concept exercises to practice exercises, but instead use on the practice exercises defined at https://github.com/exercism/problem-specifications/tree/main/exercises.

**Comment by pokrakam** [comment]
Thanks, could you please check if PR #128 is what you mean? I did see a reference to `## General` in the docs and was a little confused why it didn't appear in the JS version.

**Comment by pokrakam** [comment]
Hmm, still not showing up. Trying without subheadings.

**Comment by pokrakam** [comment]
OK, had another go with PR #129 and it is still not showing any hints. 
What is wrong with https://github.com/exercism/abap/blob/main/exercises/practice/custom-signs/.docs/hints.md ? 
(apart from one small typo which I'll fix in the next iteration)

**Comment by pokrakam** [comment]
Ah, never mind, you need to update the exercise to get the hints to appear. They're working now!
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/25539927/161724844-cf16180a-1ecf-40f0-b23e-3dc3f3a33187.png">

**Comment by ErikSchierboom** [comment]
👍
