### ISSUE TITLE
Acronym

### ISSUE THREAD

**Issue by mickrig** [exercism/abap#233]
I have an issue with Acronym excercise. I provided a solution, but I get an error if I use an exception class which seems it is unknown in exercism. The solution works fine in an on-prem system.
![image](https://user-images.githubusercontent.com/38348938/197406540-c46c1fe9-7fec-4745-837d-03884d4d18a3.png)

**Comment by kotp** [comment]
You provided a solution that apparently raises an error.  That error is not expected, though.

Do the tests pass locally?

You may want to request mentoring so that a mentor can help you work through the exercise.  If there is an issue, then they may direct you here to open one.

I suspect that it is simply that the tests are not expecting to have the try/catch performed, or not result in the way that it is used here.

**Comment by larshp** [comment]
yea, the exception class is probably missing in the runtime

https://help.sap.com/doc/abapdocu_731_index_htm/7.31/en-US/abensegment_functions.htm

**Comment by mickrig** [comment]
> You provided a solution that apparently raises an error. That error is not expected, though.
> 
> Do the tests pass locally?
> 
> You may want to request mentoring so that a mentor can help you work through the exercise. If there is an issue, then they may direct you here to open one.
> 
> I suspect that it is simply that the tests are not expecting to have the try/catch performed, or not result in the way that it is used here.

Locally the tests pass. The exception is the expected behaviour when the appropriate index is not found.
I think it would work when the exception class has been added to the runtime.

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/954

**Comment by mickrig** [comment]
Hi Lars, thanks it works now.
